name: Create Release

on:
  push:   
    branches: 
      - 'release-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/heads\/release-/}
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
        server-id: DOCKER_REGISTRY
        server-username: DOCKER_REGISTRY_USERNAME
        server-password: DOCKER_REGISTRY_PASSWORD
    - name: View settings
      run: cat /home/runner/.m2/settings.xml
    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"        
    - name: Perform Release
      run: mvn --batch-mode --update-snapshots -B -Dtag=${GITHUB_REF##*release-} -Darguments="-Dmaven.deploy.skip=true" release:prepare release:perform
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
